"""Shared policy constants."""

MAX_SEMANTIC_CANDIDATES = 500
MAX_RESONANCE_CANDIDATES = 200
RESONANCE_HOP_DECAY = 0.6
RESONANCE_MAX_EDGES_PER_NODE = 8
RESONANCE_CONVERGENCE_CAP = 2.0
LINK_DECAY_HALF_LIFE_DAYS = 90.0
CO_RECALL_WEIGHT_STEP = 0.05
CO_RECALL_WEAKEN_STEP = 0.1
LEGACY_CONTEXT_OWNER = "__legacy_unscoped_context__"
CO_RECALL_INITIAL_WEIGHT = 0.2
NEGATIVE_FEEDBACK_CONFIDENCE_STEP = 0.05
SUPERSEDED_SCORE_PENALTY = 0.4

AUTO_LINK_WEIGHT = 0.3
AUTO_LINK_LIMIT = 5
CONSOLIDATION_MIN_CLUSTER_WEIGHT = 0.6
CONSOLIDATION_MIN_ACTIVATIONS = 3
CONSOLIDATION_MIN_CLUSTER_SIZE = 3
RETENTION_MIN_HALF_LIVES = 4.0

# Federation sync
SYNC_MAX_FUTURE_SKEW_SECONDS = 300
SYNC_HTTP_TIMEOUT_SECONDS = 30

# Pairing
PAIRING_INVITE_TTL_SECONDS = 600
PAIRING_REDEEM_TIMEOUT_SECONDS = 15

# CLI network and process waits
TEAM_UPDATE_REQUEST_TIMEOUT_SECONDS = 20
PYPI_REQUEST_TIMEOUT_SECONDS = 6
PROCESS_LIST_TIMEOUT_SECONDS = 10
PROCESS_ELAPSED_QUERY_TIMEOUT_SECONDS = 5
SCHEDULED_TASK_QUERY_TIMEOUT_SECONDS = 10
STALE_PROCESS_START_SLACK_SECONDS = 90
WEB_RESTART_POLL_ATTEMPTS = 40
WEB_RESTART_POLL_INTERVAL_SECONDS = 0.25
WEB_RESTART_LIVENESS_DELAY_SECONDS = 1.0

# Discovery
DISCOVERY_PORT_PROBE_TIMEOUT_SECONDS = 0.5
DISCOVERY_HEALTH_PROBE_TIMEOUT_MULTIPLIER = 4

# Fleet requests
FLEET_HTTP_TIMEOUT_SECONDS = 10

# Memory decay defaults
DEFAULT_DECAY_HALF_LIFE_DAYS = {
    "preference": 180.0,
    "fact": 90.0,
    "procedure": 365.0,
    "environment": 30.0,
    "decision": 180.0,
    "warning": 365.0,
    "note": 30.0,
}
DEFAULT_DECAY_HALF_LIFE_FALLBACK_DAYS = 30.0

# Native service policy
SYSTEMD_RESTART_DELAY_SECONDS = 3

# Instance settings
SETTINGS_PORT_PROBE_TIMEOUT_SECONDS = 0.3
SETTINGS_PORT_SEARCH_LIMIT = 64

# Shadow-mode latency policy
SHADOW_P99_LATENCY_TARGET_MILLISECONDS = 200.0
SHADOW_P99_LATENCY_PAUSE_MILLISECONDS = 500.0

# Web API
WEB_FLEET_SIGNATURE_FRESHNESS_SECONDS = 120
WEB_FLEET_CONTENT_PREFIXES = (
    "/api/memories",
    "/api/search",
    "/api/recall",
    "/api/context-pack",
    "/api/orchestrate",
    "/api/archive",
    "/api/graph",
    "/api/sync/export",
)
WEB_LOG_TAIL_READ_BYTES = 2_000_000  # bounded read so huge logs can't OOM the console

# Web UI
WEB_UI_TOAST_DURATION_MILLISECONDS = 4_200
WEB_UI_GRAPH_SETTLE_FRAME_THRESHOLD = 300

# Database policy
SQLITE_BUSY_TIMEOUT_MILLISECONDS = 5_000
MEMBERSHIP_CACHE_TTL_SECONDS = 30.0
FLEET_NONCE_RETENTION_SECONDS = 600
SNAPSHOT_RETENTION_COUNT_PER_SESSION = 5
DASHBOARD_ACTIVITY_WINDOW_DAYS = 14

# Decay feedback tuning
DECAY_FEEDBACK_MIN_MULTIPLIER = 0.5
DECAY_FEEDBACK_MAX_MULTIPLIER = 4.0
DECAY_FEEDBACK_MIN_HALF_LIFE_DAYS = 7.0
DECAY_FEEDBACK_MAX_HALF_LIFE_DAYS = 730.0
# Keep the update threshold aligned with rounding precision: 10 ** -digits.
DECAY_FEEDBACK_ROUND_DIGITS = 2
DECAY_FEEDBACK_UPDATE_THRESHOLD_DAYS = 0.01

# ERA resonance prototype
# Reduced from 0.00000133 to 0.0000008 to mitigate recall drop.
ERA_PROTOTYPE_DECAY_LAMBDA_PER_SECOND = 0.0000008
ERA_PROTOTYPE_MIN_WEIGHT = 0.01
ERA_PROTOTYPE_DEFAULT_HOPS = 2
ERA_PROTOTYPE_LINK_MIN_SHARED_TERMS = 2
ERA_PROTOTYPE_LINK_MAX_TERM_DEGREE = 20
ERA_PROTOTYPE_LINK_MAX_WEIGHT = 1.0
ERA_PROTOTYPE_LINK_SHARED_TERMS_FOR_MAX_WEIGHT = 5.0
